[build]
  command = "npm run build"
  publish = "_site"

[[redirects]]
  from = "https://nicolas-hoizey-photo.netlify.com"
  to = "https://nicolas-hoizey.photo"
  status = 301
  force = true

[[redirects]]
  from = "https://nicolas-hoizey-photo.netlify.app"
  to = "https://nicolas-hoizey.photo"
  status = 301
  force = true
