[build]
  command = "npm run build"
  publish = "_site"

[[redirects]]
  from = "https://nicolas-hoizey-photo.netlify.com"
  to = "https://nicolas-hoizey.photo"
  status = 301
  force = true

[[redirects]]
  from = "https://nicolas-hoizey-photo.netlify.app"
  to = "https://nicolas-hoizey.photo"
  status = 301
  force = true

[[redirects]]
  from = "/images/:width/*"
  to = "https://res.cloudinary.com/nho/image/fetch/q_auto,f_auto,w_:width,c_limit/https://nicolas-hoizey.photo/:splat"
  status = 200

[[redirects]]
  from = "/diaporama/:width/*"
  to = "https://res.cloudinary.com/nho/image/fetch/q_auto,f_auto,g_auto,w_:width,ar_3:2,c_fill/https://nicolas-hoizey.photo/:splat"
  status = 200

[[headers]]
  for = "/ui/*"
    [headers.values]
    Cache-Control = "public, max-age=86400"
